version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - chmod +x gradlew
      - echo "Start build"
      - ./gradlew clean build

artifacts:
  files:
    - build/libs/*.jar